### PR TITLE
Updated gradle to work with Android Studio 3.0. Updated dependencies.…

### PR DESCRIPTION
**Pull request by tpincumbe**
… Updated Travis.

### CODE REVIEW

**Comment by sddamico** [comment]
dunno why these tests are failing, are they failing for you locally?

**Comment by tpincumbe** [comment]
yeah, they are. i'm going through the changes 1 by 1 to see what breaks it. i think it's mostly due to updating mockito from 1.10.19 to 2.7.6. i've never used mockito before, so i'll see if i can get it working w/o updating the version number for that.

**Comment by sddamico** [comment]
Ahh interesting. Thanks for picking this back up!

**Comment by tpincumbe** [comment]
So I downgraded mockito back to 1.10.19 and the tests pass again. i've never used mockito before, so idk what to change to get it working on the latest version. i did go ahead and update okhttp to 3.10.0 and fixed the code to make it work. also, i added in kotlin support.

**Comment by asadmshah** [comment]
@sddamico Are there plans to move this project to Kotlin? Just weird to see the dependency being brought in without it being used.

**Comment by sddamico** [comment]
@asadmshah I think that concern is valid. I've created a PR to remove it until it has a use case here: #76

**Pull request merged**
